// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWXO1_uDdtm0W55xvOwGcjM37yihHXjHU',
    appId: '1:839877112202:web:69cd35f6fbd60f2f201873',
    messagingSenderId: '839877112202',
    projectId: 'swync-eed37',
    authDomain: 'swync-eed37.firebaseapp.com',
    storageBucket: 'swync-eed37.appspot.com',
    measurementId: 'G-YJ3N3NYFNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNh1uiKLgtgJZlT6QNKts681G0T427ZAo',
    appId: '1:839877112202:android:1ecd80ae1007748e201873',
    messagingSenderId: '839877112202',
    projectId: 'swync-eed37',
    storageBucket: 'swync-eed37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJvikqSZgkAziKxT3kvUXMG-Z431elqI',
    appId: '1:839877112202:ios:69b05f1356db08a7201873',
    messagingSenderId: '839877112202',
    projectId: 'swync-eed37',
    storageBucket: 'swync-eed37.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJvikqSZgkAziKxT3kvUXMG-Z431elqI',
    appId: '1:839877112202:ios:b8eba09e8082f3e4201873',
    messagingSenderId: '839877112202',
    projectId: 'swync-eed37',
    storageBucket: 'swync-eed37.appspot.com',
    iosBundleId: 'com.example.testDrive.RunnerTests',
  );
}
